### ISSUE TITLE
Переупаковка магазинов

### ISSUE THREAD

**Issue by sanosit** [ss220-space/arma3#1]
**Описание:**
- Добавление простого скрипта с понятным ( но английским ) интерфейсом, который позволяет переупаковать магазины.

**План:**
- Шаг 1 - https://steamcommunity.com/sharedfiles/filedetails/?id=755210821 (достаточно)
- Шаг 2 - Выудить в блокнот и закинуть в папку со сценарием.
- Шаг 3 - Прописать "exec имя_блокнота" в исполняемый файл.
- Шаг 4 - Вы великолепны!

**Вознаграждение:**
- Денег нет, извините.

**Дополнительная информация:**
- Вроде был старый баг, что при переупаковке полного магазина, теряется 1 патрон. Не считаю, что это особо критично. В любом случае, данный скрипт имеет нормальный интерфейс, что выделяет его среди аналогов.

**Comment by ShieldNavalny** [comment]
Сделано с коммитом #8a1f318e8a6261922337df2e4e99d52b13ae2ee8

Демо: 
https://youtu.be/sPH---VHC0g
