### ISSUE TITLE
Первичный ребаланс стоимости техники РФ

### ISSUE THREAD

**Issue by RedokPaw** [ss220-space/arma3#11]
**Понижение стоимости конкретной техники:**
В целях получения хоть какой-то играбельности за РФ до введения полноценного нового баланса, нужны первые правки по цене:

- **БТР-60ПБ** 3000 ---> 1700
- **БТР-70** 3150 ---> 1800
- **БТР-80** 3250 ---> 1900
- **БТР-80А** 3500 ---> 3250
- **БМД-1** 4500---> 4000
- **БМД-1Р** 4500---> 4000
- **БМП-1К** 4500---> 3500
- **БМП-2К** 5000 ---> 4000
- **2C25** 5000 --->  4500

**Comment by RedokPaw** [comment]
- **БМД-4М** 5000 ---> 4750

Прикладываю **уже измененный Description файл**, 
[description.txt](https://github.com/ss220-space/arma3/files/8557188/description.txt)
работоспособность проверена (формат TXT)

**Comment by ShieldNavalny** [comment]
@RedokPaw будет смержено с последующим пулл-реквестом. 
Для любых последующих изменений необходимо создавать пулл-реквест из форка и линкить сюда. 
Для примера см. #1 issue

**Comment by ArlordGS** [comment]
https://github.com/ss220-space/arma3/pull/20#issue-1215623781

**Comment by ShieldNavalny** [comment]
Выполнено пулл-реквестом #20
