### ISSUE TITLE
Выбор класса

### ISSUE THREAD

**Issue by RedokPaw** [ss220-space/arma3#12]
Так-как мы имеем очень жесткие рамки выбора спецификации слота, нужно сделать их универсальными, а при входе давать игроку выбор класса

Примеры классов:

- КО
- Стрелок
- ПТ Стрелок
- Стрелок с ПВО
- Пулеметчик
- Снайпер
- Инженер
- Медик
И другие

Так же нужно будет составить для классов сбалансированный набор вооружения.

**Comment by ArlordGS** [comment]
https://github.com/ArlordGS/arma3/tree/patch-1

- Добавлены классы для обоих сторон
- Требуется проверка присуждения роли медика и инженера (попробывал проверить на уазике, колёса ставит, а вот движок починить не смог, поэтому не уверен работает ли)
- Помимо классов было изменено меню закупки
   -Амерам заменил имбовый хантер, на более приземлёный мрап.
   - Русским добавил Уазики с ДШКМ, АГС и СПГ, добавил БМД-3.
   - Выпелил КА-60 у Русских, снизил цену на траспортные вертолёты русским.
