### ISSUE TITLE
Бесполезный аеродром 

### ISSUE THREAD

**Issue by Egorium** [ss220-space/arma3#23]
В данный момент я не вижу никакого смысла в аэродроме, просто точка и всё. Мне кажется было бы интереснее воевать за аеродром не просто как за точку, а как за единственное место где можно взять вертолётики, а с баз в свою очередь вертолётные площадки убрать

**Comment by ShieldNavalny** [comment]
На текущий момент данное нововведение будет дисбалансным. 
Также прошу в будущем заполнять согласно форме запросов нововведений.
