### ISSUE TITLE
Попробовать новый TS сервер

### ISSUE THREAD

**Issue by Bizzonium** [ss220-space/arma3#28]
**Описание:**
- Со старым публичным есть проблемы с сообщениями о спаме

**План:**
- Поменять адрес с `5g5.net` на `178.62.217.192` 
- Посмотреть, будут ли проблемы

**Дополнительная информация:**
 "<21:16:31> Действие невозможно выполнить из-за защиты от спама. Подождите несколько секунд и повторите попытку."

**Comment by Bizzonium** [comment]
Ошибся, кодом ничего менять не надо

**Comment by ShieldNavalny** [comment]
Надо.
