### ISSUE TITLE
Дать возможность переносить стационары

### ISSUE THREAD

**Issue by ArlordGS** [ss220-space/arma3#3]
**Описание:**
- В данный момент стационары можно спавнить только в зонах и их нельзя перетаскивать, разобрать или загрузить в технику. Добавить возможность перетаскивать, разбирать или же загружать стационары в технику, 

**План:**
- Установка ACE на сервер (будут все возможности сразу)
 - Написания скрипта под это дело (очерёдной костыль, трудоёмкий)

**Вознаграждение:**
- Благодарочка

**Comment by ShieldNavalny** [comment]
@ArlordGS предоставьте пожалуйста, какое улучшение требуется добавить а не пресет Issue :)

**Comment by ArlordGS** [comment]
Описание:

Дать возможность перетаскивать стационары
План:
Установить ACE на сервер
