### ISSUE TITLE
недобаг со снарягой

### ISSUE THREAD

**Issue by Cerberus7711** [ss220-space/arma3#52]
при выбое класса гранатомётчика с РПГ-7B2 выдавалcя sa vz. 58v с обвесами ПНВ(gen4) маска с очками, шлем 6б 47, gorka-R и 6b23 vest.После смерти спавнит в шлеме 6б28,без пнв, с ак-74м без обвесов,EPM-пустыня,6b23 лето.короче недобаг с снарягой

**Comment by ShieldNavalny** [comment]
Есть специальная форма для багов. Ничего не понятно.
Какая миссия? Что предполагается выдавать? При каких условиях происходит?

Откройте пожалуйста заново с нормальным описанием
