### ISSUE TITLE
Десинхроны от 3 лица при ревайве

### ISSUE THREAD

**Issue by RedokPaw** [ss220-space/arma3#9]
В некоторых ситуациях нокнутые люди после ревайва могут снова бегать и стрелять, однако от 3 лица все еще лежат мертвыми и говорят.

**Comment by ShieldNavalny** [comment]
Требуются дополнительные пояснения. Что значит от третьего лица? Также необходимы клиентские RPT-логи. 

И переоформите пожалуйста ТЕКУЩИЙ issue согласно форме
https://github.com/ss220-space/arma3/issues/new?assignees=&labels=bug&template=bug-report.md

**Comment by ShieldNavalny** [comment]
Система ревайвов убрана и заменена на бессознательные состояния ACE с #36. 
Также не были предоставлены дополнительные сведения о баге поэтому issue считается закрытым
